### ISSUE TITLE
Adapter only sees tests change once

### ISSUE THREAD

**Issue by tyrsius** [MortenHoustonLudvigsen/KarmaTestAdapter#8]
We are running with Cassette to package up our JavaScript files. When we build the project it copies them from source into a directory that karma is looking at. The first time Visual Studio starts the test adapter correctly finds all the current tests, and will update after a single build. Subsequent builds do not see the newer versions of the tests. Restarting visual studio works, but this is quite cumbersome to do after every change.

This didn't start happening until we updated to 0.8.2. Previously we were on version 0.7.x, which did not have this issue.

**Comment by MortenHoustonLudvigsen** [comment]
@tyrsius
Have you tried supplying the tests files the adapter should watch in `karma-vs-reporter.json`. For example:

````JSON
"TestFiles": [ "test/**/*test.js" ]
````

I will be concentrating on #9, which I hope will solve these and other issues.

**Comment by tyrsius** [comment]
@MortenHoustonLudvigsen Yes, we have been doing that. Again, this was working correctly until we updated. I appreciate that you want to focus on another issue, but why close this before it has been verified as resolved?

**Comment by MortenHoustonLudvigsen** [comment]
@tyrsius I apologize if you feel that I have close this issue hastily. I have now reopened it.

A prerelease of the next version is available at [v1.0.0-alpha.1](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/releases/tag/v1.0.0-alpha.1). I very much hope this solves the issues you have been having. Also, from now on I will be attaching the vsix file to each release in GitHub, so that it will be easy to go back to an earlier version, if a new version is faulty.

**Comment by MortenHoustonLudvigsen** [comment]
@tyrsius Hopefully this issue should be resolved in version 1.0.0 of the adapter.

Please reopen this issue if this is not the case.
